_welcome:
    pattern:  /
    defaults: { _controller: AueioClubBundle:Game:list }

AueioClubBundle:
    resource: "@AueioClubBundle/Controller/"
    type:     annotation
    prefix:   /

_assetic:
    resource: .
    type:     assetic

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
