_welcome:
    pattern:  /
    defaults: { _controller: AueioClubBundle:Team:welcome }

AueioClubBundle:
    resource: "@AueioClubBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile_show:
    pattern:   /profile/
    defaults:  { _controller: AueioClubBundle:Player:show}
    
fos_user_profile_edit:
    pattern:   /profile/edit
    defaults:  { _controller: FOSUserBundle:Profile:edit}

    
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
