jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_PLAYER:    ROLE_USER
        ROLE_LEADER:    ROLE_PLAYER
        ROLE_ADMIN:     ROLE_LEADER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile, role: ROLE_USER }
        - { path: ^/player/edit, role: ROLE_LEADER }
        - { path: ^/player/contact, role: ROLE_PLAYER }
        - { path: ^/player/delete, role: ROLE_PLAYER }
        - { path: ^/game/selection, role: ROLE_PLAYER }
        - { path: ^/game/sheet, role: ROLE_LEADER }
        - { path: ^/game/score, role: ROLE_PLAYER }
        - { path: ^/game/new, role: ROLE_LEADER }
        - { path: ^/game/edit, role: ROLE_LEADER }
        - { path: ^/game/delete, role: ROLE_LEADER }
        - { path: ^/team/new, role: ROLE_ADMIN }
        - { path: ^/team/edit, role: ROLE_LEADER }
        - { path: ^/team/contact, role: ROLE_PLAYER }
        - { path: ^/team/delete, role: ROLE_ADMIN }
