security:
    providers:
        fos_userbundle:
            id: fos_user.user_manager
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/player, role: ROLE_USER }
        - { path: ^/game/selection, role: ROLE_USER }
        - { path: ^/game/sheet, role: ROLE_USER }
        - { path: ^/game/score, role: ROLE_USER }
        - { path: ^/game/new, role: ROLE_ADMIN }
        - { path: ^/game/edit, role: ROLE_ADMIN }
        - { path: ^/game/delete, role: ROLE_ADMIN }
        - { path: ^/team/new, role: ROLE_ADMIN }
        - { path: ^/team/edit, role: ROLE_ADMIN }
        - { path: ^/team/delete, role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
            