parameters:
#    aueio_club.example.class: Aueio\ClubBundle\Example

services:
#    aueio_club.example:
#        class: %aueio_club.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
services:
   aueio_player.registration.form.type:
        class: Aueio\ClubBundle\Form\Type\PlayerRegistrationType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: aueio_player_registration }

   aueio_player.form.handler.registration:
        class: Aueio\ClubBundle\Form\Handler\PlayerRegistrationHandler
        arguments: ["@fos_user.registration.form", "@request", "@fos_user.user_manager", "@fos_user.mailer", "@doctrine.orm.entity_manager"]
        scope: request
        public: false
   aueio_player.profile.form.type:
        class: Aueio\ClubBundle\Form\Type\PlayerProfileType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: aueio_player_profile }
   aueio_player.form.handler.profile:
        class: Aueio\ClubBundle\Form\Handler\PlayerProfileHandler
        arguments: ["@fos_user.profile.form", "@request", "@fos_user.user_manager", "@fos_user.mailer"]
        scope: request
        public: false
        