# Aueio/ClubBundle/Resources/config/validation.yml
Aueio\ClubBundle\Entity\Player:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
                     fields: [firstname, lastname]
                     message: aueio_club.name.already_used
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
                     fields: phone
                     message: aueio_club.phone.already_used
    properties:
        firstname:
            - NotBlank: ~
            - MaxLength: 50
            - Type:
                 type: string
        lastname:
            - NotBlank: ~
            - MaxLength: 50
            - Type:
                 type: string
        gender:
            - MaxLength: 1
            - Choice: [M, F]
        phone:
            - NotBlank: ~
            - Type:
                 type: string
            - MinLength: 10
            - MaxLength: 10
        position:
            - NotBlank: ~
            - Choice: [GOAL, PIVOT, CENTER, BACK, WING]
        car:
            - Type:
                type: bool
        hand:
            - MaxLength: 6
            - Choice: [LEFT, RIGHT]

Aueio\ClubBundle\Entity\Team:
    properties:
        name:
            - NotBlank: ~
            - MaxLength: 50
            - Type:
                 type: string
        slot_start_time:
            - NotBlank: ~
            - Type: \DateTime
        slot_end_time:
            - NotBlank: ~
            - Type: \DateTime
        colors:
            - NotBlank: ~
            - Type:
                 type: array
        gym_name:
            - NotBlank: ~
            - MaxLength: 50
            - Type:
                 type: string
        gym_phone:
            - NotBlank: ~
            - Type:
                 type: string
            - MinLength: 10
            - MaxLength: 10

Aueio\ClubBundle\Entity\Game:
    properties:
        date:
            - NotBlank: ~
            - Type: \DateTime
        start_time:
            - NotBlank: ~
            - Type: \DateTime
        end_time:
            - NotBlank: ~
            - Type: \DateTime
        comment:
            - MaxLength: 500
            - Type:
                 type: string

Aueio\ClubBundle\Entity\Role:
    properties:
        type:
            - MaxLength: 7
            - Choice: [VISITOR, LOCAL]
        score:
            - Type:
                 type: integer

Aueio\ClubBundle\Entity\Config:
    properties:
        secret:
            - NotBlank: ~
            - MaxLength: 255
             