# Aueio/ClubBundle/Resources/config/validation.yml
Aueio\ClubBundle\Entity\Player:
    properties:
        firstname:
            - NotBlank: ~
            - MaxLength: 50
            - Type:
                 type: string
        lastname:
            - NotBlank: ~
            - MaxLength: 50
            - Type:
                 type: string
        surname:
            - NotBlank: ~
            - MaxLength: 50
            - Type:
                 type: string
        gender:
            - MaxLength: 1
            - Choice: [M, F]
        phone:
            - NotBlank: ~
            - Type:
                 type: string
            - MinLength: 10
            - MaxLength: 10
        adress:
            - NotBlank: ~
            - Type:
                 type: string
            - MaxLength: 255
        position:
            - NotBlank: ~
            - Choice: [GOAL, PIVOT, CENTER, BACK, WING]
        car:
            - Type:
                type: bool
        hand:
            - MaxLength: 6
            - Choice: [LEFT, RIGHT]

Aueio\ClubBundle\Entity\Team:
    properties:
        name:
            - NotBlank: ~
            - MaxLength: 50
            - Type:
                 type: string
        adress:
            - NotBlank: ~
            - Type:
                 type: string
            - MaxLength: 255

Aueio\ClubBundle\Entity\Game:
    properties:
        startTime:
            - NotBlank: ~
            - Type: \DateTime
        endTime:
            - NotBlank: ~
            - Type: \DateTime
        comment:
            - MaxLength: 500
            - Type:
                 type: string
Aueio\ClubBundle\Entity\Role:
    properties:
        type:
            - MaxLength: 7
            - Choice: [VISITOR, LOCAL]
        score:
            - Type:
                 type: integer
Aueio\ClubBundle\Entity\Config:
    properties:
        secret:
            - NotBlank: ~
            - MaxLength: 255
             