<?php

namespace Aueio\ClubBundle\Repository;

use Doctrine\ORM\EntityRepository,
	Aueio\ClubBundle\Entity\Team;

/**
 * ActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository
{
	public function getStats(Team $team)
	{
		$stats = array();
		foreach ( array("local", "visitor", "giveup") as $type ){
			$res = $this->findByType($team, $type);
			if(is_array($res)){
				$stats[$type] = count($res);
			}
		}
		foreach ( array("win", "lost", "nul") as $result ){
			$res = $this->findByResult($team, $result);
			if(is_array($res)){
				$stats[$result] = count($res);
			}
		}
		
		return $stats;
	}
	public function findByType(Team $team, $type){
		
		return $this->createQueryBuilder('r')
		->join('r.team', 't')
		->where('t.id = :id_team')
		->andWhere('r.type = :type')
		->setParameters(array(
				'id_team' => $team->getId(),
				'type' => $type
		))
		->getQuery()->getResult();
	}
	public function findByResult(Team $team, $result){
		return $this->createQueryBuilder('r')
		->join('r.team', 't')
	 	->where('t.id = :id_team')
		->andWhere('r.result = :result')
		->setParameters(array(
				'id_team' => $team->getId(),
				'result' => $result
		))
		->getQuery()->getResult();
	}
	
}