<?php

namespace Aueio\ClubBundle\Repository;

use Doctrine\ORM\EntityRepository,
	Doctrine\ORM\Mapping\ClassMetadata,
	Doctrine\ORM\EntityManager,
	Doctrine\DBAL\Types\Type as DBALType;

/**
 * ActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeasonAwareRepository extends EntityRepository
{
	/**
	 * @param unknown_type $em
	 * @param Mapping\ClassMetadata $class
	 */
	public function __construct(EntityManager $em, ClassMetadata $class) {
		$season_id = $this->container->get('request')->getSession()->get('season_id');
		$em->getFilters()->getFilter('season')->setParameter('season_id', $season_id, DBALType::INTEGER);
		parent::__construct($em, $class);
	}

}