<?php

namespace Aueio\ClubBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeasonRepository extends EntityRepository
{
	public function findAllOrdered()
	{
		return $this->createQueryBuilder('s')
		->orderBy('s.start_date' , 'DESC')
		->getQuery()->getResult();
	}
	public function findByDate(\DateTime $date)
	{
		
		$query =  $this->createQueryBuilder('s')
		->where('s.start_date < :date')
		->andWhere('s.end_date > :date')
		->setMaxResults(1)
		->setParameters(array(
				'date' => $date->format("Y-m-d"),
		))
		->getQuery();
		try {
			$season = $query->getSingleResult();
		} catch (\Doctrine\Orm\NoResultException $e) {
			$season = null;
		}
		return $season;
	}
	public function findCurrent(){
		$season = $this->findByDate(new \DateTime('now'));
		if(!$season){
			$seasons = $this->findAllOrdered();
			if(count($seasons) > 0){
				$season = $seasons[0];
			}
		}
		return $season;
	}
}