<?php

namespace Aueio\ClubBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeasonRepository extends EntityRepository
{
	public function findAllOrdered()
	{
		return $this->createQueryBuilder('s')
		->orderBy('s.startDate' , 'DESC')
		->getQuery()->getResult();
	}
	public function findByDate(\DateTime $date)
	{
		return $this->createQueryBuilder('s')
		->where('s.startDate < :date')
		->andWhere('s.endDate > :date')
		->setMaxResults(1)
		->setParameters(array(
				'date' => $date->format("Y-m-d"),
		))
		->getQuery()->getSingleResult();
	}
}