<?php

namespace Aueio\ClubBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends EntityRepository
{
	public function findSeasonAll($season_id){
		return $this->createQueryBuilder('t')
		->leftJoin('t.seasons', 's')
		->where('s.id = :id_season')
		->orderBy('t.name')
		->setParameters(array(
				'id_season' => $season_id,
		))
		->getQuery()->getResult();
	}
}